export const RecentProperties = [
  {
    property_id: "001",
    property_type: "rent",
    property_name: "Contemporary 5 Bedroom Home",
    property_img: "/Listing/list1.jpg",
    property_price: "₦530,000,000",
    property_details: "Fully Detached Duplex with modern amenities",
    property_location: "Lekki Phase 1, Lagos",
    inner_details: [
      "🛌 5 Bedrooms",
      "🚽 5 Bathrooms",
      " 🖼️ 2 Living Rooms",
      "🏊‍♀️ Swimming Pool",
    ],
  },
  {
    property_id: "002",
    property_type: "sell",
    property_name: "4 Bedroom Maisonette",
    property_img: "/Listing/list2.jpg",
    property_price: "₦750,000,000",
    property_details: "Luxury Maisonette with premium finishes",
    property_location: "Ikoyi, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      "🚽 4 Bathrooms",
      "💪 Gym",
      "📷 CCTV Surveillance",
    ],
  },
  {
    property_id: "003",
    property_type: "sell",
    property_name: "5 Bedroom Fully Detached Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦900,000,000",
    property_details: "Spacious duplex with BQ and swimming pool",
    property_location: "Lekki Phase 1, Lagos",
    inner_details: [
      "🛌 5 Bedrooms",
      "🚽6 Bathrooms",
      "🖼️2 Living Rooms",
      "🏊‍♀️Private Pool",
    ],
  },
  {
    property_id: "004",
    property_type: "rent",
    property_name: "3 Bedroom Terrace Duplex",
    property_img: "/Listing/list4.jpg",
    property_price: "₦8,000,000",
    property_details: "Modern terrace duplex in a serene environment",
    property_location: "Ologolo, Lekki, Lagos",
    inner_details: [
      "🛌3 Bedrooms",
      "🚽3 Bathrooms",
      " 🍽️ Fitted Kitchen",
      "🔐 24/7 Security",
    ],
  },
  {
    property_id: "005",
    property_type: "rent",
    property_name: "4 Bedroom Semi-Detached Duplex",
    property_img: "/Listing/list5.jpg",
    property_price: "₦7,500,000",
    property_details: "Elegant semi-detached duplex with modern amenities",
    property_location: "Osapa, Lekki, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      "🚽 4 Bathrooms",
      "🛤️ BQ",
      "🚘 Ample Parking Space",
    ],
  },
  {
    property_id: "006",
    property_type: "sell",
    property_name: "Luxury 3 Bedroom Bungalow",
    property_img: "/Listing/list6.jpg",
    property_price: "₦65,000,000",
    property_details: "Fully furnished bungalow in a gated estate",
    property_location: "Amen Estate, Ibeju Lekki, Lagos",
    inner_details: [
      "🛌 3 Bedrooms",
      "🚽 3 Bathrooms",
      "🍽️ Fitted Kitchen",
      "💡 24/7 Power Supply",
    ],
  },
  {
    property_id: "007",
    property_type: "sell",
    property_name: "5 Bedroom Detached Duplex",
    property_img: "/Listing/list7.jpg",
    property_price: "₦85,000,000",
    property_details: "Spacious duplex with modern finishes",
    property_location: "Ajah, Lagos",
    inner_details: [
      "🛌5 Bedrooms",
      "🚽 5 Bathrooms",
      "🏊‍♀️ Swimming Pool",
      "📷 CCTV Surveillance",
    ],
  },
  {
    property_id: "008",
    property_type: "sell",
    property_name: "4 Bedroom Terrace Duplex",
    property_img: "/Listing/list8.jpg",
    property_price: "₦75,000,000",
    property_details: "Stylish terrace duplex in a prime location",
    property_location: "Ikota, Lekki, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      "🚽 4 Bathrooms",
      "🍽️ Fitted Kitchen",
      "🔐 24/7 Security",
    ],
  },
  {
    property_id: "009",
    property_type: "sell",
    property_name: "6 Bedroom Fully Detached Duplex",
    property_img: "/Listing/list9.jpg",
    property_price: "₦150,000,000",
    property_details: "Luxurious duplex with state-of-the-art facilities",
    property_location: "Ikoyi, Lagos",
    inner_details: [
      "🛌 6 Bedrooms",
      "🚽 6 Bathrooms",
      "🛗 Private Elevator",
      "📽️ Home Cinema",
    ],
  },
  {
    property_id: "0010",
    property_type: "sell",
    property_name: "3 Bedroom Block of Flats",
    property_img: "/Listing/list10.jpg",
    property_price: "₦90,000,000",
    property_details: "Well-maintained block of flats with ample parking",
    property_location: "Ikotun, Lagos",
    inner_details: [
      "🛌 3 Bedrooms",
      "🚽 3 Bathrooms",
      "🍽️ Fitted Kitchen",
      "💡 24/7 Power Supply",
    ],
  },
  {
    property_id: "0011",
    property_type: "rent",
    property_name: "4 Bedroom Semi-Detached Duplex",
    property_img: "/Listing/list11.jpg",
    property_price: "₦35,000,000",
    property_details: "Affordable semi-detached duplex in a serene environment",
    property_location: "Igando, Lagos",
    inner_details: [
      " 🛌4 Bedrooms",
      "🚽 4 Bathrooms",
      "🍽️ Fitted Kitchen",
      "🚘 Ample Parking Space",
    ],
  },
  {
    property_id: "0012",
    property_type: "sell",
    property_name: "5 Bedroom Duplex with BQ",
    property_img: "/Listing/list12.jpg",
    property_price: "₦120,000,000",
    property_details: "Spacious duplex with BQ and modern amenities",
    property_location: "Osapa London Estate, Lekki, Lagos",
    inner_details: [
      "🛌 5 Bedrooms",
      "🚽 5 Bathrooms",
      "🏊‍♀️ Swimming Pool",
      "🔐 24/7 Security",
    ],
  },
  {
    property_id: "0013",
    property_type: "sell",
    property_name: "4 Bedroom Fully Detached Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦95,000,000",
    property_details: "Elegant detached duplex with premium finishes",
    property_location: "Orchid, Lekki, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      "🚽 4 Bathrooms",
      "🍽️ Fitted Kitchen",
      "📷 CCTV Surveillance",
    ],
  },
  {
    property_id: "0014",
    property_type: "sell",
    property_name: "5 Bedroom Fully Detached Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦165,000,000",
    property_details: "Luxurious duplex with state-of-the-art facilities",
    property_location: "Lekki, Lagos",
    inner_details: [
      "🛌 5 Bedrooms",
      "🚽 5 Bathrooms",
      "🏊‍♀️ Swimming Pool",
      "📽️ Home Cinema",
    ],
  },
  {
    property_id: "0015",
    property_type: "rent",
    property_name: "4 Bedroom Semi-Detached Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦65,000,000",
    property_details: "Affordable semi-detached duplex in a gated estate",
    property_location: "Lekki, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      "🚽 4 Bathrooms",
      "🍽️ Fitted Kitchen",
      "💡24/7 Power Supply",
    ],
  },
  {
    property_id: "0016",
    property_type: "sell",
    property_name: "4 Bedroom Terrace Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦55,000,000",
    property_details: "Stylish terrace duplex with modern amenities",
    property_location: "Orchid, Lekki, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      " 🚽4 Bathrooms",
      "🍽️ Fitted Kitchen",
      "🚘 Ample Parking Space",
    ],
  },
  {
    property_id: "0017",
    property_type: "sell",
    property_name: "5 Bedroom Fully Detached Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦225,000,000",
    property_details: "Luxurious duplex with swimming pool and BQ",
    property_location: "Lekki, Lagos",
    inner_details: [
      "🛌 5 Bedrooms",
      "🚽 5 Bathrooms",
      "🏊‍♀️ Swimming Pool",
      "🔐 24/7 Security",
    ],
  },
  {
    property_id: "0018",
    property_type: "sell",
    property_name: "4 Bedroom Maisonette",
    property_img: "/Listing/list3.jpg",
    property_price: "₦140,000,000",
    property_details: "Elegant maisonette with premium finishes",
    property_location: "Ikoyi, Lagos",
    inner_details: [
      "🛌 4 Bedrooms",
      "🚽 4 Bathrooms",
      "🍽️ Fitted Kitchen",
      "📷 CCTV Surveillance",
    ],
  },
  {
    property_id: "0019",
    property_type: "sell",
    property_name: "3 Bedroom Terrace Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦80,000,000",
    property_details: "Modern terrace duplex in a serene environment",
    property_location: "Ajah, Lagos",
    inner_details: [
      "🛌 3 Bedrooms",
      "🚽 3 Bathrooms",
      "🍽️ Fitted Kitchen",
      "💡24/7 Power Supply",
    ],
  },
  {
    property_id: "0020",
    property_type: "rent",
    property_name: "5 Bedroom Fully Detached Duplex",
    property_img: "/Listing/list3.jpg",
    property_price: "₦100,000,000",
    property_details: "Spacious duplex with modern amenities",
    property_location: "Ikate, Lekki, Lagos",
    inner_details: [
      "🛌 5 Bedrooms",
      "🚽 5 Bathrooms",
      "🏊‍♀️ Swimming Pool",
      "📽️ Home Cinema",
    ],
  },
];
